name: 'VTEX IO App Cypress'
description: 'Run Cypress tests on VTEX IO apps'
author: VTEX
inputs:
  account:
    required: true
    description: 'VTEX Account'
  app-key:
    required: true
    description: 'APP Key used for authenticating with Toolbelt'
  app-token:
    required: true
    description: 'APP Token used for authenticating with Toolbelt'
  test-repository:
    description: 'Repository containing Cypress tests (e.g. vtex/my-app-tests)'
  test-repository-ref:
    description: 'Ref to repository containing Cypress tests (e.g. main)'
  link-retries:
    description: 'Amount of retries to do on link failure'
    default: 3
  spec:
    description: 'Spec regex for Cypress tests'
runs:
  using: 'composite'
  steps:
    - name: Clone app repository
      uses: actions/checkout@v3
      with:
        path: io-app
    - name: Clone test repository
      if: ${{ inputs['test-repository'] }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs['test-repository'] }}
        ref: ${{ inputs['test-repository-ref'] }}
        path: tests
    - uses: vtex/action-toolbelt-login@v1
      id: login
      with:
        account: ${{ inputs.account }}
        app-key: ${{ inputs['app-key'] }}
        app-token: ${{ inputs['app-token'] }}
    - name: Clone action repo
      uses: actions/checkout@v3
      with:
        repository: vtex/action-io-app-cypress
        path: io-action
    - uses: ./io-action/.github/actions/create-workspace
      with:
        workspace: e2e${{ github.sha }}
        account: ${{ inputs.account }}
        token: ${{ steps.login.outputs.token }}
    - name: Install toolbelt
      shell: bash
      run: |
        yarn global add vtex
        echo "$(yarn global bin)" >> $GITHUB_PATH
    - name: Link app
      uses: nick-fields/retry@v2
      with:
        max_attempts: ${{ inputs['link-retries'] }}
        timeout_minutes: 5
        command: |
          cd io-app
          yes | vtex link --no-watch
        shell: bash
    - name: Cypress
      uses: cypress-io/github-action@v4
      with:
        spec: ${{ inputs.spec }}
        working-directory: ${{ inputs['test-repository'] == '' && 'io-app' || 'tests' }}
      env:
        CYPRESS_VTEX_WORKSPACE: e2e${{ github.sha }}
        CYPRESS_APP_KEY: ${{ inputs['app-key'] }}
        CYPRESS_APP_TOKEN: ${{ inputs['app-token'] }}
        COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
        COMMIT_INFO_AUTHOR: ${{ github.actor }}
