name: 'VTEX Create Workspace'
description: 'Create temporary VTEX IO workspace'
author: VTEX
inputs:
  account:
    required: true
    description: 'VTEX account'
  workspace:
    required: true
    description: 'Workspace name'
  token:
    required: true
    description: 'Authentication token for VTEX APIs'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
